# Generated by Django 3.2 on 2021-04-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo_carrera', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('carnet_docente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=50)),
                ('apellido_docente', models.CharField(max_length=50)),
                ('nombre_rol', models.CharField(max_length=25)),
                ('departamento', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('carnet_estudiante', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre_estudiante', models.CharField(max_length=50)),
                ('apellido_estudiante', models.CharField(max_length=50)),
                ('sexo_estudiante', models.CharField(max_length=1)),
                ('telefono_estudiante', models.IntegerField()),
                ('correo_estudiante', models.CharField(max_length=100)),
                ('direccion_estudiante', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo_proyecto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion_proyecto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstudioUniversitario',
            fields=[
                ('carnet_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyecto.estudiante')),
                ('codigo_carrera', models.CharField(max_length=10)),
                ('codigo_ciclo', models.IntegerField()),
                ('porc_carrerar_aprob', models.IntegerField()),
                ('unidades_valorativas', models.IntegerField()),
                ('experiencia_areas_conoc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('carnet_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyecto.estudiouniversitario')),
                ('codigo_entidad', models.CharField(max_length=10)),
                ('horas_semana', models.IntegerField()),
                ('dias_semana', models.IntegerField()),
                ('modalidad', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('carnet_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyecto.solicitud')),
                ('aceptado', models.CharField(max_length=30)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('carnet_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proyecto.solicitud')),
                ('carnet_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.docente')),
                ('codigo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
        ),
    ]
