# Generated by Django 3.2 on 2021-04-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigoDepartamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=100)),
                ('nombreJefeDepartamento', models.CharField(max_length=50)),
                ('apellidoJefeDepartamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.departamento'),
        ),
    ]
