# Generated by Django 3.2 on 2021-04-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210429_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.departamento'),
        ),
    ]
