# Generated by Django 3.2 on 2021-05-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('fecha_modificacion', models.DateField()),
                ('hora_modificacion', models.TimeField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
