# Generated by Django 3.2 on 2021-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('GER', 'Gerente'), ('TAC', 'Táctico')], default='EST', max_length=3),
        ),
    ]
